[build]
  command = "npm run build"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle client-side routing (Vue/React SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
